server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:\GIT\git-local-repo
          default-label=main:
          uri: https://github.com/RDDcat/MSAEcommerceDemo
#          username: [username]
#          password: [password]